#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-phabricator
Version  : 0.9.1
Release  : 12
URL      : https://files.pythonhosted.org/packages/a9/c0/4e3bf742d2e9af6873bdb7a82cd2d376e9f80519c511d871f394d1be0bf6/phabricator-0.9.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/a9/c0/4e3bf742d2e9af6873bdb7a82cd2d376e9f80519c511d871f394d1be0bf6/phabricator-0.9.1.tar.gz
Summary  : Phabricator API Bindings
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-phabricator-license = %{version}-%{release}
Requires: pypi-phabricator-python = %{version}-%{release}
Requires: pypi-phabricator-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(requests)

%description
python-phabricator
==================
.. image:: https://travis-ci.org/disqus/python-phabricator.png?branch=master
:target: https://travis-ci.org/disqus/python-phabricator

%package license
Summary: license components for the pypi-phabricator package.
Group: Default

%description license
license components for the pypi-phabricator package.


%package python
Summary: python components for the pypi-phabricator package.
Group: Default
Requires: pypi-phabricator-python3 = %{version}-%{release}

%description python
python components for the pypi-phabricator package.


%package python3
Summary: python3 components for the pypi-phabricator package.
Group: Default
Requires: python3-core
Provides: pypi(phabricator)
Requires: pypi(requests)

%description python3
python3 components for the pypi-phabricator package.


%prep
%setup -q -n phabricator-0.9.1
cd %{_builddir}/phabricator-0.9.1
pushd ..
cp -a phabricator-0.9.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1666741966
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-phabricator
cp %{_builddir}/phabricator-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-phabricator/248796de217d49dc2ea3bb234a15a0aec0526c0d || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-phabricator/248796de217d49dc2ea3bb234a15a0aec0526c0d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
